CREATE DATABASE server_db;
CREATE USER server WITH PASSWORD 'app_strong_pass_for_server_user';
GRANT CONNECT ON DATABASE server_db TO server;
\c server_db
GRANT USAGE ON SCHEMA public TO server;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO server;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO server;